name: Deploy Hexo Site

on:
  push:
    branches: [ main ]  # 监听main分支的推送
  
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 拉取完整历史，确保分类和标签正确生成
      
      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # 缓存npm依赖，加快构建速度
      
      - name: 安装依赖
        run: npm install
      
      - name: 安装Hexo CLI
        run: npm install -g hexo-cli
      
      - name: 清理并构建网站
        run: |
          npm list --depth=0
          hexo --version
          hexo clean
          hexo generate --debug
      
      - name: 查看部署配置
        run: |
          cat _config.yml | grep -A 10 deploy
          echo "检查Git配置"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --list
      
      - name: 部署到GitHub Pages
        run: |
          echo "开始部署..."
          set -x
          hexo deploy --debug || {
            echo "部署失败，尝试直接推送到gh-pages分支"
            cd public
            git init
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git add .
            git commit -m "Deploy from GitHub Actions"
            git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}